# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: windows-2019

steps:
- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: '$(system.defaultWorkingDirectory)/test.ps1'
  timeoutInMinutes: 120
- task: CopyFiles@2
  displayName: 'Copy Artifact Files to: $(build.artifactstagingdirectory)'
  inputs:
      Contents: |
        Logs\**
      TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

     
   
