# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: windows-2019

steps:
- task: AzurePowerShell@4
  inputs:
    targetType: inline
    pwsh: true
    script: |
     $PSVersionTable
     Install-Module AzureAD -AllowClobber -Force
     $module=Get-Module -ListAvailable|Where-Object{$_.Name -eq 'AzureAD'}
     Import-Module $module -UseWindowsPowerShell
   
